version: '3'

services:
  web:
    build:
      context: .
      dockerfile: "./apps/nginx-reverse-proxy/Dockerfile"
    ports:
      - "80:80"
    networks:
      - backend

  auth-service:
    container_name: "auth-service"
    build:
      dockerfile: ./apps/auth/Dockerfile
      context: .
    
    environment:
      - CLIENT_URL=${CLIENT_URL}
      - MONGO_URL=${MONGO_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - HOST=0.0.0.0
      - DOMAIN=${DOMAIN}
    
    networks:
      - backend

  mail-service:
    container_name: "mail-services"
    build:
      context: .
      dockerfile: ./apps/mail-services/Dockerfile
    
    environment:
      - CLIENT_URL=${CLIENT_URL}
      - MONGO_URL=${MONGO_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SESSION_SECRET=${SESSION_SECRET}
      - EMAIL_PORT=${EMAIL_PORT}
      - HOST=0.0.0.0
      - TEMP_FILE=/app/apps/mail-services/src/temp/

    networks:
      - backend

  extract-service:
    container_name: "extract-service"
    build:
      context: ./apps/extract-service
      dockerfile: Dockerfile

    environment:
      - MONGO_URL=${MONGO_URL}
    
    networks:
      - backend

networks:
  backend:
